### ISSUE TITLE
No backup of _CodeSignature is made :/

### ISSUE THREAD

**Issue by maciboy** [aonez/NightShiftPatcher#3]
Hi,
I'm in a bit of trouble with my Mojave installation...
Everything worked fine, especially the new Home.app.
Then I applied the Nightshift patch:
After an unsuccessful patch because of missing Xcode, patching worked and NightShift was usable through system preferences...
BUT: Home.app does not work any more because it CoreBrightness.framework is said to be not iOS (!!!) compatible!
_Dyld Error Message:
  Library not loaded: /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness
  Referenced from: /System/iOSSupport/System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities
  Reason: no suitable image found.  Did find:
	/System/Library/PrivateFrameworks/CoreBrightness.framework/CoreBrightness: mach-o, but not built for iOSMac
	/System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness: mach-o, but not built for iOSMac
	/System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness: mach-o, but not built for iOSMac_

So I wanted to revert back, but unfortunately your script only backed up the framework file, not the _CodeSignature :(
This means that I'm currently stuck with a system with **unsigned CoreBrightness.framework, no NightShift and no Home.app** 😭

**Comment by aonez** [comment]
Only the binary of the framework is modified. The backup is also only from that file:

`/System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness`


Replace the backup file, found in the desktop, then codesign again:

```sh
sudo codesign -f -s - /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness
```

**Comment by aonez** [comment]
Note that I’ve not tested this script in Mojave, since I don’t have any Mac capable of running it.

**Comment by maciboy** [comment]
Thanks for this very quick reply!
Since other patchers for nightshift also back up the CodeSignature I thought it would be necessary here, too...
I was not aware, that I can sign the file with such a command. 

Will try now :)

PS: my MacBook Pro 2010 is also unsupported, but thanks to Mojave Patcher, I was able to install it :P

**Comment by maciboy** [comment]
I‘m afraid the file that should be the backup is not „good enough“:
Signing worked, but Home still says that the framework is „not built for iOSMac“

I will try to obtain the unmodified CoreBrightness.framework file from another Mojave user at the MacRumors forum.
Do you think I can use the file coming from and machine or does it Need to be also from a MacBook Pro 2010 15“ (6,2)?

**Comment by maciboy** [comment]
Done :)
I got a CoreBrightness.framework file from another Mojave user...
Now Night Shift AND Home.app are working 👍

**Comment by aonez** [comment]
I’m pretty sure the file will be the same for any machine, only the beta version needs I be the same. Will change the backup to do the complete framework... sorry about that!

**Comment by aonez** [comment]
So how did you enable it finally? With this script and manually copying the code signature? Or maybe just using the vanilla framework, so the patch does not need to be applied again?

I’m reopening this since fixing it would make a Mojave compatible script.

**Comment by aonez** [comment]
I’m reopening this since fixing it would make a Mojave compatible script.

**Comment by maciboy** [comment]
Honestly, I don't really know which steps were needed to get it working again.
When Finder said that the signature is wrong, I took the framework including signature from High Sierra. This then lead to "not iOSMac compatible"....

The step that cured it for me was pasting the Mojave framework, which I got through macrumors forum, and sign it with the command you provided.
The received framework was already enabling Nightshift, so I did not need to apply your script...:
https://forums.macrumors.com/threads/macos-10-14-mojave-on-unsupported-macs-thread.2121473/page-239#post-26380101

**Comment by aonez** [comment]
Thanks @maciboy! I'll try to do some tests.

**Comment by Squuiid** [comment]
@aonez were you able to make any headway with this?
It sounds promising and a fix would make it the first and only Mojave compatible NightShift patch available :)

**Comment by aonez** [comment]
@Squuiid Sunday is a good day to try this things.

**Comment by aonez** [comment]
I'll need to use [this method](https://forums.macrumors.com/threads/macos-10-14-mojave-on-unsupported-macs-thread.2121473/) to really try the patch on Mojave, since the virtual machine on Parallels "works" (has the option enabled but causes not effect to apply Night Shift) with and without the patch.

So wish me luck and give me some patience.

**Comment by aonez** [comment]
@Squuiid after a long Sunday, I can say **the script worked without any modification needed** on a Mac Mini 3.1 running 10.14 beta 11. This machine needs SIP to be disabled, so I can't check if enabling it will break the modification. Anyway I've improved a little the script, with a few checks.

@maciboy the script now saves the entire framework here:
```
/System/Library/PrivateFrameworks/CoreBrightness.framework.bak
```

**Comment by Squuiid** [comment]
> @Squuiid after a long Sunday, I can say **the script worked without any modification needed** on a Mac Mini 3.1 running 10.14 beta 11. This machine needs SIP to be disabled, so I can't check if enabling it will break the modification. Anyway I've improved a little the script, with a few checks.
> 
> @maciboy the script now saves the entire framework here:
> 
> ```
> /System/Library/PrivateFrameworks/CoreBrightness.framework.bak
> ```

Awesome, thank you so much! And Home app works fine after patching also? There were reports of a broken Home app due to the CoreBrightmess mod.
Again, thank you very much for your efforts on this, I and many others will greatly appreciate your work. Thank you.

**Comment by Squuiid** [comment]
UPDATE: It works perfectly. Ran script and then re-enabled SIP on my 5,1 cMP and Night Shift (and Home app) works great! Thanks again @aonez

**Comment by aonez** [comment]
Thanks for the test @Squuiid! Applying it in another machine found some other bugs that are fixed now, and also a double check of the framework signature, this is the reason it does not boot on some machines after the patch.

Thanks both!

**Comment by Squuiid** [comment]
I ran it a few hours ago on another Mac Pro and unfortunately it failed. When I rebooted Finder would no longer run. My Mac Pro is in an unusable state at the moment. I'll have to take a look and see if I can fix from the command line as finder no longer runs. Any ideas would be welcome ;)
The script complained about one of the command line tools not being available despite nm being there and the tools installed.

**Comment by aonez** [comment]
@Squuiid you can also run in single mode (when starting the Mac press and hold command+s) if needed, but since the Terminal.app works for you, easier.

Check the signature status:
```
codesign --verify --deep --verbose=2 --strict /System/Library/PrivateFrameworks/CoreBrightness.framework
```

If it says other than "valid on disk" this is the error.

Use the backup:
```
mv -f /System/Library/PrivateFrameworks/CoreBrightness.framework.bak /System/Library/PrivateFrameworks/CoreBrightness.framework
```

The version you've used introduced an extra file by error in the backup, simply remove it:
```
rm /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness.tmp
```

Recheck the signature of the backup with the first code, it must be valid now. Restart, hopefully with all working properly, and reapply the updated patch. You can paste here the script output, in case it fails :)

Let me know how it goes!

**Comment by Squuiid** [comment]
Thanks @aonez . Finder now working but the signature of the reinstated backup gives the following. Everything works for now (except Night Shift) but can't seem to re-apply patch.

sudo codesign --verify --deep --verbose=2 --strict /System/Library/PrivateFrameworks/CoreBrightness.framework

/System/Library/PrivateFrameworks/CoreBrightness.framework: a sealed resource is missing or invalid

I'm assuming I won't be able to re-enable SIP if the code is not signed properly.
Don't worry too much. I will be wiping this Mac once Mojave goes GM. For now it's working well enough ;)

**Comment by Squuiid** [comment]
This is the error I get if I try and run again now.

NightShiftPatcher.sh: line 16: [: ==: unary operator expected
-e 
NightShiftPatcher by aONe ® 2017 (https://github.com/aonez/NightShiftPatcher)
-e Original idea by Pike (https://pikeralpha.wordpress.com/2017/01/30/4398)
-e Motivated by NightPatch (https://github.com/pookjw/NightPatch)


Checking for requirements...
-e SIP is disabled
-e Binary nm is functional
Looking for minimum requirements check offset...
-e Offset: 0x44260
Getting offset hex data...
-e Original hex: 00044260: 0900 0000 0100 0000 0d00 0000 0600 0000 0500 0000 0600 0000  ........................
Cloning the framework...
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack/Versions/A/CoreBrightness
Replacing offset hex data...
24+0 records in
24+0 records out
24 bytes transferred in 0.000206 secs (116508 bytes/sec)
Checking offset hex replaced...
-e Replaced hex: 00044260: 0100 0000 0100 0000 0100 0000 0100 0000 0100 0000 0100 0000  ........................
Resigning the framework...
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack: replacing existing signature
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack: code object is not signed at all
In subcomponent: /System/Library/PrivateFrameworks/CoreBrightness.framework.hack/Versions/Current/CoreBrightness.temp
Checking new signature...
-e 
The new signature is invalid or can't be applied. Check the original framework sigature is valid and try again. No patch applied.
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack: invalid signature (code or signature have been modified)
In architecture: x86_64

**Comment by aonez** [comment]
> sudo codesign --verify --deep --verbose=2 --strict /System/Library/PrivateFrameworks/CoreBrightness.framework
> 
> /System/Library/PrivateFrameworks/CoreBrightness.framework: a sealed resource is missing or invalid

You need to delete the file introduced by error in the backup:
```
rm /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness.tmp
```

**Comment by Squuiid** [comment]
> > sudo codesign --verify --deep --verbose=2 --strict /System/Library/PrivateFrameworks/CoreBrightness.framework
> > /System/Library/PrivateFrameworks/CoreBrightness.framework: a sealed resource is missing or invalid
> 
> You need to delete the file introduced by error in the backup:
> 
> ```
> rm /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness.tmp
> ```

I had tried but this is what it gave :(

rm /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness.tmp
rm: /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness.tmp: No such file or directory

**Comment by Squuiid** [comment]
> > > sudo codesign --verify --deep --verbose=2 --strict /System/Library/PrivateFrameworks/CoreBrightness.framework
> > > /System/Library/PrivateFrameworks/CoreBrightness.framework: a sealed resource is missing or invalid
> > 
> > 
> > You need to delete the file introduced by error in the backup:
> > ```
> > rm /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness.tmp
> > ```
> 
> I had tried but this is what it gave :(
> 
> rm /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness.tmp
> rm: /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness.tmp: No such file or directory

Aha! It's temp not tmp :)

ls /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/
CoreBrightness		CoreBrightness.temp	Resources		_CodeSignature

Deleted and now it works! Code signed. Will try running again. Thanks again!

**Comment by aonez** [comment]
> Resigning the framework...
> /System/Library/PrivateFrameworks/CoreBrightness.framework.hack: replacing existing signature
> /System/Library/PrivateFrameworks/CoreBrightness.framework.hack: code object is not signed at all
> In subcomponent: /System/Library/PrivateFrameworks/CoreBrightness.framework.hack/Versions/Current/CoreBrightness.temp

Sorry I did not seen that before in your log 🤦🏻‍♂️

**Comment by Squuiid** [comment]
Bingo! It now works perfectly. Fantastic work, thank you very much.
Night Shift enabled 👍

**Comment by aonez** [comment]
@Squuiid sorry for the troubleshooting... and thanks for it. Now the script is smarted thanks to you 👍

**Comment by Squuiid** [comment]
> @Squuiid sorry for the troubleshooting... and thanks for it. Now the script is smarted thanks to you 👍

No worries, happy to do it. Thank you for all the time you have put into this!
