### ISSUE TITLE
Restore backup

### ISSUE THREAD

**Issue by fotisman** [aonez/NightShiftPatcher#4]
How do I revert to the backup?

**Comment by fotisman** [comment]
Notification Centre keeps crashing, no backlit keyboard, please help

**Comment by aonez** [comment]
Hi @fotisman! The backup should be located here:

```sh
/System/Library/PrivateFrameworks/CoreBrightness.framework.bak
```

If you used an old `NightShiftPatcher` script, first remove this file from the backup:

```sh
rm '/System/Library/PrivateFrameworks/CoreBrightness.framework.bak/Versions/Current/CoreBrightness.temp'
```

To restore the backup with the terminal, use this terminal line:

```sh
f='/System/Library/PrivateFrameworks/CoreBrightness.framework'; mv "${f}" "${f}.hack"; mv "${f}.bak" "${f}";
```

Let me know if this helps.

**Comment by aonez** [comment]
By the way @fotisman, what macOS are your running?

**Comment by fotisman** [comment]
10.13.6 on a MacBookPro8.2 (15” Early 2011-i7 2.3-matte screen)

**Comment by aonez** [comment]
> matte screen

Lucky you

**Comment by fotisman** [comment]
It wasn’t just luck, I was looking for months for this particular model

**Comment by fotisman** [comment]
Do you think there’s any chance of your patch working without any problems on my machine?
I mean in the near or not-so-near future?

**Comment by aonez** [comment]
If you're able to troubleshoot and do some tests, I'm mostly positive it will work. You've used the latest script? It was updated on Sept 18.

**Comment by fotisman** [comment]
Yep, I’ve used the latest script.

**Comment by fotisman** [comment]
I'll need your help and guidance through troubleshooting, though

**Comment by aonez** [comment]
Sure. First restore the backup, and see if it works as expected. If this is ok, reapply the script and copy/paste all the output here.

**Comment by fotisman** [comment]
What do you mean «really the script»?
I have already restored the backup, in a clumsy way (using the Finder), before you responded, and everything seems to work OK

**Comment by aonez** [comment]
Reapply the script, it was a typo :)

So reapply the script and paste here all the output. You can execute it like this:

```sh
NightShiftPatcher.sh > ~/Desktop/NightShiftPatcher.log
```

That way all the output is in the log file and you can simply zip and share it with me here. You can also just copy paste the terminal text.

**Comment by fotisman** [comment]
I’m in the middle of some serious translating work right now, so maybe the timing is not perfect to reapply the script, I’ ll try later.
The terminal text from last night’s attempt goes like this: MOVED TO THE COMMENT BELOW

**Comment by aonez** [comment]
> I’ ll try later

When you can.

```log
Password:

/Users/fotis/Downloads/NightShiftPatcher-master/NightShiftPatcher.sh: line 16: [: ==: unary operator expected

NightShiftPatcher by aONe ® 2017 (https://github.com/aonez/NightShiftPatcher)
Original idea by Pike (https://pikeralpha.wordpress.com/2017/01/30/4398)
Motivated by NightPatch (https://github.com/pookjw/NightPatch)


Checking for requirements...
SIP is disabled
Binary nm is functional
Looking for minimum requirements check offset...
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Offset: 0x
Getting offset hex data...
Original hex: 00000000: cffa edfe 0700 0001 0300 0000 0600 0000 1800 0000 f00e 0000  ........................
Cloning the framework...
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack/Versions/A/CoreBrightness
Replacing offset hex data...
24+0 records in
24+0 records out
24 bytes transferred in 0.000156 secs (153684 bytes/sec)
Checking offset hex replaced...
Replaced hex: 00000000: 0100 0000 0100 0000 0100 0000 0100 0000 0100 0000 0100 0000  ........................
Resigning the framework...
Checking new signature...
New signature checked
Creating a backup at "/System/Library/PrivateFrameworks/CoreBrightness.framework.bak"...
Using the patched version...


All done now :)
```

> xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

This is the problem. Maybe you have more than one partition in that machine? Maybe a partition with Mojave?

Let me know if this command outputs the help without any issue:

```sh
nm -help
```

Also let me know what this command  outputs:

```sh
which nm
```

**Comment by fotisman** [comment]
Last login: Tue Oct  2 14:37:24 on ttys010
Makis:~ fotis$ nm -help
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Makis:~ fotis$ 
————————————
Makis:~ fotis$ which nm
/usr/bin/nm

**Comment by aonez** [comment]
Can you execute those commands:

```sh
xcode-select -p; xcrun --show-sdk-path; xcrun --show-sdk-version; xcrun --show-sdk-platform-path;
```

**Comment by fotisman** [comment]
Makis:~ fotis$ xcode-select -p
/Library/Developer/CommandLineTools
Makis:~ fotis$ xcrun --show-sdk-path
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Makis:~ fotis$ xcrun --show-sdk-version
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Makis:~ fotis$ xcrun --show-sdk-platform-path
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by aonez** [comment]
@fotisman do you have the Xcode.app?

**Comment by fotisman** [comment]
Nope, do I need it?

**Comment by fotisman** [comment]
Or do I just need the CommandLineTools?

**Comment by aonez** [comment]
No, it's not needed, just the command line tools. Execute this one and let me know if it launches the installer (install then) or if it says it's already installed.

```sh
xcode-select --install
```

No disk partitions then?

**Comment by fotisman** [comment]
It’s installing right now.

**Comment by aonez** [comment]
Wow ok, so that was it. I'll update the script right now.

**Comment by fotisman** [comment]
So, what next?

**Comment by aonez** [comment]
When the installation finishes, just check the `nm -help` outputs the help properly. If it does, I'm 99% sure the script will work for you.

You can execute this code before to double check:

```sh
nm "/System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness" | grep _ModelMinVersion | cut -d' ' -f 1 | sed -e 's/^0*//g' | head -1
```

It must output an alphanumeric code, like `37c80`.

I'll update the script to install the command line tools when your error is found. This case was not contemplated. But now that you've manually installed the tools you can run the script as it is now.

Also I'll add a check so if the alphanumeric code is not found, the script does stop.

**Comment by fotisman** [comment]
So, is it OK?

Makis:~ fotis$ nm -help
USAGE: nm [options] <input files> --s...

Makis:~ fotis$ nm "/System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness" | grep _ModelMinVersion | cut -d' ' -f 1 | sed -e 's/^0*//g' | head -1
37c80

**Comment by fotisman** [comment]
Tried to run the patch and this is what I got on the terminal

Resigning the framework...
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack: replacing existing signature
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack: code object is not signed at all
In subcomponent: /System/Library/PrivateFrameworks/CoreBrightness.framework.hack/Versions/Current/CoreBrightness.tbd
Checking new signature...

The new signature is invalid or can't be applied. Check the original framework sigature is valid and try again. No patch applied.
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack: invalid signature (code or signature have been modified)
In architecture: x86_64

**Comment by aonez** [comment]
> /System/Library/PrivateFrameworks/CoreBrightness.framework.hack/Versions/Current/CoreBrightness.tbd

I don't know what this file is... Let me know what this outputs:

```sh
ls -l /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/Current/
```

**Comment by fotisman** [comment]
Makis:~ fotis$ ls -l /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/Current/
total 1240
-rwxr-xr-x  1 root  wheel  632240  2 Οκτ 00:03 CoreBrightness
-rw-r--r--  1 root  wheel     509 23 Ιολ 06:21 CoreBrightness.tbd
drwxr-xr-x  5 root  wheel     160  1 Οκτ 23:51 Resources
drwxr-xr-x  3 root  wheel      96  1 Οκτ 23:51 _CodeSignature

**Comment by aonez** [comment]
> CoreBrightness.tbd

Remove that one and apply the patch again:

```sh
sudo rm /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/Current/CoreBrightness.tbd
```

**Comment by fotisman** [comment]
I’ll restart now. Fingers crossed…
If anything goes wrong again what’s the command to restore the original CoreBrightness file?

**Comment by aonez** [comment]
```sh
f='/System/Library/PrivateFrameworks/CoreBrightness.framework'; mv "${f}" "${f}.hack"; mv "${f}.bak" "${f}";
```

I'm implementing this in the script, so running the script with `-r` option will restore the backup.

**Comment by fotisman** [comment]
This is how it looks on the terminal
Makis:~ fotis$ sudo /Users/fotis/Downloads/NightShiftPatcher-master/NightShiftPatcher.sh 

/Users/fotis/Downloads/NightShiftPatcher-master/NightShiftPatcher.sh: line 16: [: ==: unary operator expected

NightShiftPatcher by aONe ® 2017 (https://github.com/aonez/NightShiftPatcher)
Original idea by Pike (https://pikeralpha.wordpress.com/2017/01/30/4398)
Motivated by NightPatch (https://github.com/pookjw/NightPatch)


Checking for requirements...
SIP is disabled
Binary nm is functional
Looking for minimum requirements check offset...
Offset: 0x37c80
Getting offset hex data...
Original hex: 00037c80: 0900 0000 0100 0000 0d00 0000 0600 0000 0500 0000 0600 0000  ........................
Cloning the framework...
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack/Versions/A/CoreBrightness
Replacing offset hex data...
24+0 records in
24+0 records out
24 bytes transferred in 0.000176 secs (136216 bytes/sec)
Checking offset hex replaced...
Replaced hex: 00037c80: 0100 0000 0100 0000 0100 0000 0100 0000 0100 0000 0100 0000  ........................
Resigning the framework...
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack: replacing existing signature
Checking new signature...
New signature checked
Creating a backup at "/System/Library/PrivateFrameworks/CoreBrightness.framework.bak"...
Using the patched version...


All done now :)

**Comment by fotisman** [comment]
Are you doing it right now?

**Comment by aonez** [comment]
> Are you doing it right now?

Yep, working with you hehe

**Comment by fotisman** [comment]
Do I have to safe boot to run this command?

**Comment by aonez** [comment]
It's not working? You just need to boot in a special mode if the normal one does not work.

**Comment by fotisman** [comment]
Haven’t tried it yet. What do you mean special mode? Single-User mode?

**Comment by aonez** [comment]
> What do you mean special mode? Single-User mode?

Yes.

> Do I have to safe boot to run this command?

I thought you where asking that.

**Comment by fotisman** [comment]
Worked!
Shows up in the Preferences and the Notifications Centre.
No glitches so far!
Thank!
Fotis Mantzoros

**Comment by aonez** [comment]
The patch is already fixed so this does not happen again :)

**Comment by aonez** [comment]
Closing this one, thanks a lot for the feedback @fotisman!
