### ISSUE TITLE
New signature invalid?

### ISSUE THREAD

**Issue by sparky672** [aonez/NightShiftPatcher#5]
I'm getting the following issue on a Sierra system that I upgraded to High Sierra and tried to patch...

> The new signature is invalid or can't be applied. Check the original framework sigature is valid and try again. No patch applied.
> /System/Library/PrivateFrameworks/CoreBrightness.framework.hack: invalid signature (code or signature have been modified)
> In architecture: x86_64

Same machine with a fresh install of High Sierra did not give me any problems at all.  However, my working drive is the one I upgraded from Sierra... what to do?  Thanks.

------

I caused the problem by not removing [the other NightShift patcher](https://github.com/pookjw/NightPatch) I used in Sierra.  Now I'm stuck.  Help.

**Comment by sparky672** [comment]
Finally got the Pookjw NightPatch completely removed. Then I was able to install this patcher without any trouble.

**Comment by aonez** [comment]
Glad to see you’ve solved that. The file you had was already patched, so a fesh framework was needed. Salut!

**Comment by sparky672** [comment]
Installed latest High Sierra security update from today, which immediately removed Night Shift.  Now your patcher is giving the `The new signature is invalid or can't be applied` error again...

```
Checking for requirements...
SIP is disabled
Binary nm is functional
Looking for minimum requirements check offset...
Offset: 0x44670
Getting offset hex data...
Original hex: 00044670: 0900 0000 0100 0000 0d00 0000 0600 0000 0500 0000 0600 0000  ........................
Cloning the framework...
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack/Versions/A/CoreBrightness
Replacing offset hex data...
24+0 records in
24+0 records out
24 bytes transferred in 0.000149 secs (161061 bytes/sec)
Checking offset hex replaced...
Replaced hex: 00044670: 0100 0000 0100 0000 0100 0000 0100 0000 0100 0000 0100 0000  ........................
Resigning the framework...
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack: replacing existing signature
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack: code object is not signed at all
In subcomponent: /System/Library/PrivateFrameworks/CoreBrightness.framework.hack/Versions/Current/CoreBrightness.tbd
Checking new signature...

The new signature is invalid or can't be applied. Check the original framework sigature is valid and try again. No patch applied.
/System/Library/PrivateFrameworks/CoreBrightness.framework.hack: invalid signature (code or signature have been modified)
In architecture: x86_64
```

Suggestions?  Thank you.

**Comment by sparky672** [comment]
Okay, so I did a restore from last backup with a `-r` and then applied the patch.  This time it worked.

Can't this whole thing be made more foolproof?  Like why can't it check the signature first, and then automatically restore from backup, and then apply the patch all at once?

**Comment by aonez** [comment]
Are you using the latest script? This was supposedly fixed a few days ago.

If updating the script does not help, try this:
https://github.com/aonez/NightShiftPatcher/issues/6#issuecomment-435654028

**Comment by aonez** [comment]
Did not read your last comment. This was fixed here https://github.com/aonez/NightShiftPatcher/commit/dadfb41c77d549527029e9dff20fc01eeea27706

**Comment by sparky672** [comment]
> Are you using the latest script? This was supposedly fixed a few days ago.

I went to this link below and the latest script is version 1.0.0 from October 2, which is the same version of the script I already have.

https://github.com/aonez/NightShiftPatcher/releases

**Comment by aonez** [comment]
I’ve made no release or version bump 😓

**Comment by sparky672** [comment]
> I’ve made no release or version bump 😓

Well that's confusing.

Should I download latest and reapply then?

**Comment by aonez** [comment]
No need to, the `-r` already fixed the issue. I’m working on a GUI solution more foolproof 👍🏼

**Comment by sparky672** [comment]
Awesome!
