### ISSUE TITLE
Doesn't work with 10.14.1

### ISSUE THREAD

**Issue by friolz** [aonez/NightShiftPatcher#6]
I get an "unsigned signature" error. I suppose this is due to 10.14.1. Can you affirm that?

**Comment by aonez** [comment]
Did you used the latest version of the script?

**Comment by aonez** [comment]
If so, run this code and let me know what it says:

```sh
codesign --verify --deep --verbose=2 --strict /System/Library/PrivateFrameworks/CoreBrightness.framework
```

**Comment by aonez** [comment]
Execute this and try again:

```sh
sudo rm /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/Current/CoreBrightness.tbd
```

Let me know if that solves the issue 😊

 It's odd because the latest script (from Oct 2) deletes that file if it's found...

**Comment by aonez** [comment]
> It's odd because the latest script (from Oct 2) deletes that file if it's found...

My bad, it only removes that file when restoring the backup. Must fix that one! Thanks!

**Comment by friolz** [comment]
Yes, latest script.
SIP is disabled.

This is what I get:
`/System/Library/PrivateFrameworks/CoreBrightness.framework: a sealed resource is missing or invalid
file added: /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/Current/CoreBrightness.tbd`

**Comment by friolz** [comment]
Now it’s working! Thanks!
