### ISSUE TITLE
Sunset to Sunrise option for Nightshift geolocation issue

### ISSUE THREAD

**Issue by MrCapone** [aonez/NightShiftPatcher#8]
When I trying enable the "Sunset to Sunrise" option for Nightshift a pop-up informs me that it "requires location for time zone to be enabled". But i already have all options on for geolocation in privacy settings.

**Comment by aonez** [comment]
This has nothing to do with the patch. I just can recommend you to be sure to have the "Setting Time Zone" check activated.

**Comment by MrCapone** [comment]
Yes problem was not with patch. It was macOS itself. I already found solution and leave it here so maybe it will help some one with same problem. 

1. Uncheck all system privacy options.
2. Reboot your mac
3. Enable all system privacy options again.

So easy. It is High Sierra bug maybe.

**Comment by aonez** [comment]
@MrCapone thanks! Sure, this might be a OS bug.
